let practiceChars=[],practiceIndex=0,userStrokes=[],currentStroke=null;
const expectedStrokeCache={};
let lastPracticeScores=[];

function pctx(){const c=$("practiceCanvas"),x=c.getContext("2d");x.lineCap="round";x.lineJoin="round";return x}
function resetPracticeResult(){const r=$("practiceResult");r.className="practiceResult";r.innerHTML="";}
function clearPracticeCanvas(){const c=$("practiceCanvas"),x=pctx();x.clearRect(0,0,c.width,c.height);userStrokes=[];currentStroke=null;lastPracticeScores=[];resetPracticeResult();$("practiceInfo").textContent="白いマスに、1画ずつ書いてみよう。";$("nextPracticeBtn").disabled=true}
function redrawPractice(scores=null){const c=$("practiceCanvas"),x=pctx();x.clearRect(0,0,c.width,c.height);userStrokes.forEach((s,i)=>{if(s.length<2)return;x.beginPath();s.forEach((p,j)=>{if(j===0)x.moveTo(p.x,p.y);else x.lineTo(p.x,p.y)});x.lineWidth=12;x.strokeStyle=scores?(scores[i]>=68?"#2f7d48":"#d95d4f"):"#30343c";x.stroke()})}
function cp(ev){const c=$("practiceCanvas"),r=c.getBoundingClientRect();return{x:(ev.clientX-r.left)*c.width/r.width,y:(ev.clientY-r.top)*c.height/r.height,pressure:ev.pressure||.5}}
function beginInk(ev){ev.preventDefault();resetPracticeResult();$("nextPracticeBtn").disabled=true;const p=cp(ev);currentStroke=[p];userStrokes.push(currentStroke);try{$("practiceCanvas").setPointerCapture(ev.pointerId)}catch(e){}}
function moveInk(ev){if(!currentStroke)return;ev.preventDefault();const p=cp(ev),prev=currentStroke[currentStroke.length-1],x=pctx();x.beginPath();x.moveTo(prev.x,prev.y);x.lineTo(p.x,p.y);x.lineWidth=10+Math.min(1,p.pressure)*8;x.strokeStyle="#30343c";x.stroke();currentStroke.push(p)}
function endInk(ev){if(!currentStroke)return;ev.preventDefault();currentStroke=null;$("practiceInfo").textContent=`今 ${userStrokes.length}画。書けたら「できたか判定」！`}
function resample(points,n=28){if(!points||points.length<2)return Array.from({length:n},()=>points&&points[0]?points[0]:{x:0,y:0});const lens=[0];let total=0;for(let i=1;i<points.length;i++){total+=Math.hypot(points[i].x-points[i-1].x,points[i].y-points[i-1].y);lens.push(total)}if(total<.001)return Array.from({length:n},()=>points[0]);const out=[];let seg=1;for(let k=0;k<n;k++){const target=total*k/(n-1);while(seg<lens.length-1&&lens[seg]<target)seg++;const a=points[seg-1],b=points[seg],den=lens[seg]-lens[seg-1]||1,t=(target-lens[seg-1])/den;out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t})}return out}
function userTo109(stroke){const c=$("practiceCanvas");return stroke.map(p=>({x:p.x/c.width*109,y:p.y/c.height*109}))}
function clamp(v,a=0,b=100){return Math.max(a,Math.min(b,v))}
function angleDiffDeg(a,b){let d=Math.abs(a-b)%(Math.PI*2);if(d>Math.PI)d=Math.PI*2-d;return d*180/Math.PI}
function scoreStroke(user,expected){if(!user||user.length<2||!expected||expected.length<2)return 0;const u=resample(userTo109(user)),e=resample(expected);let sum=0;for(let i=0;i<u.length;i++)sum+=Math.hypot(u[i].x-e[i].x,u[i].y-e[i].y);const mean=sum/u.length;const us=u[0],ue=u[u.length-1],es=e[0],ee=e[e.length-1];const ua=Math.atan2(ue.y-us.y,ue.x-us.x),ea=Math.atan2(ee.y-es.y,ee.x-es.x);const dir=angleDiffDeg(ua,ea);const endpoint=(Math.hypot(us.x-es.x,us.y-es.y)+Math.hypot(ue.x-ee.x,ue.y-ee.y))/2;const pathScore=clamp(100-mean*3.4),dirScore=clamp(100-dir*.72),posScore=clamp(100-endpoint*3.3);return Math.round(pathScore*.58+dirScore*.22+posScore*.20)}
async function expectedStrokes(ch){if(expectedStrokeCache[ch])return expectedStrokeCache[ch];const text=await fetchStrokeSvg(ch),doc=new DOMParser().parseFromString(text,"image/svg+xml");let src=[...doc.querySelectorAll('g[id*="StrokePaths"] path')];if(!src.length)src=[...doc.querySelectorAll("path")];const ns="http://www.w3.org/2000/svg",holder=document.createElementNS(ns,"svg");holder.setAttribute("viewBox","0 0 109 109");holder.style.cssText="position:fixed;left:-9999px;top:-9999px;width:109px;height:109px;opacity:0;pointer-events:none";document.body.appendChild(holder);const result=[];for(const sp of src){const p=document.createElementNS(ns,"path");p.setAttribute("d",sp.getAttribute("d"));holder.appendChild(p);const len=p.getTotalLength(),pts=[];for(let i=0;i<32;i++){const q=p.getPointAtLength(len*i/31);pts.push({x:q.x,y:q.y})}result.push(pts)}holder.remove();expectedStrokeCache[ch]=result;return result}
function practiceDots(){$("practiceCharDots").innerHTML=practiceChars.map((c,i)=>`<div class="charDot ${i<practiceIndex?"done":i===practiceIndex?"current":""}">${c}</div>`).join("")}
function startPractice(){animationToken++;document.body.classList.add("practiceMode");$("practicePanel").classList.add("show");syncAppHeight();practiceChars=[...stages[si].answer];practiceIndex=0;practiceDots();clearPracticeCanvas();$("practiceTitle").textContent=`「${practiceChars[0]}」を書いてみよう`;$("nextPracticeBtn").textContent=practiceChars.length===1?"できた！ →":"次の字 →"}
async function checkPractice(){const ch=practiceChars[practiceIndex];if(!userStrokes.length){$("practiceInfo").textContent="まず1画書いてみよう ✏️";return}const result=$("practiceResult");try{const exp=await expectedStrokes(ch),expectedCount=exp.length,countOK=userStrokes.length===expectedCount;const scores=[];for(let i=0;i<userStrokes.length;i++)scores.push(i<exp.length?scoreStroke(userStrokes[i],exp[i]):0);lastPracticeScores=scores;redrawPractice(scores);const comparable=scores.slice(0,Math.min(scores.length,expectedCount));const avg=comparable.length?Math.round(comparable.reduce((a,b)=>a+b,0)/comparable.length):0;const goodStrokes=comparable.filter(v=>v>=68).length;const orderPct=expectedCount?Math.round(goodStrokes/expectedCount*100):0;const bad=comparable.map((v,i)=>v<68?i+1:null).filter(Boolean);const passed=countOK&&avg>=70&&bad.length<=Math.max(1,Math.floor(expectedCount*.2));result.className=`practiceResult show ${passed?"good":"retry"}`;if(passed){result.innerHTML=`🎉 <strong>せいかい！</strong> 「${ch}」よく書けた！<div class="scoreRow"><span class="scoreChip">画数 ${userStrokes.length}/${expectedCount} ◎</span><span class="scoreChip">書き順 ${orderPct}%</span><span class="scoreChip">形 ${avg}点</span></div>`;$("practiceInfo").textContent="緑の線は見本に近い画だよ。";$("nextPracticeBtn").disabled=false;confetti(7)}else{const why=!countOK?`画数が ${userStrokes.length}画。見本は ${expectedCount}画だよ。`:bad.length?`${bad.slice(0,4).join("・")}画目をもう一度見てみよう。`:"形をもう少し見本に近づけてみよう。";result.innerHTML=`✏️ <strong>もう一回！</strong> ${why}<div class="scoreRow"><span class="scoreChip">画数 ${userStrokes.length}/${expectedCount} ${countOK?"◎":"△"}</span><span class="scoreChip">書き順 ${orderPct}%</span><span class="scoreChip">形 ${avg}点</span></div>`;$("practiceInfo").textContent="赤い線が、見本と違いが大きかった画。消してもう一度でもOK！";$("nextPracticeBtn").disabled=false}}catch(e){result.className="practiceResult show retry";result.innerHTML=`画数は ${userStrokes.length}画。書き順データを取得できなかったので、今回は自分で見比べよう。`;$("nextPracticeBtn").disabled=false}}
function advancePractice(){if(practiceIndex<practiceChars.length-1){practiceIndex++;practiceDots();clearPracticeCanvas();$("practiceTitle").textContent=`「${practiceChars[practiceIndex]}」を書いてみよう`;$("nextPracticeBtn").textContent=practiceIndex===practiceChars.length-1?"できた！ →":"次の字 →"}else{document.body.classList.remove("practiceMode");$("practicePanel").classList.remove("show");nextStage()}}
const pc=$("practiceCanvas");pc.addEventListener("pointerdown",beginInk,{passive:false});pc.addEventListener("pointermove",moveInk,{passive:false});pc.addEventListener("pointerup",endInk,{passive:false});pc.addEventListener("pointercancel",endInk,{passive:false});$("practiceBtn").onclick=startPractice;$("clearCanvasBtn").onclick=clearPracticeCanvas;$("undoStrokeBtn").onclick=()=>{if(userStrokes.length){userStrokes.pop();redrawPractice()}resetPracticeResult();$("practiceInfo").textContent=`今 ${userStrokes.length}画。`;$("nextPracticeBtn").disabled=true};$("checkPracticeBtn").onclick=checkPractice;$("nextPracticeBtn").onclick=advancePractice;
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))}
$("showPartsBtn").onclick=()=>{$("recall").style.display="none";$("puzzle").classList.add("show");$("feedback").textContent="1文字目からいこう！"};$("hintBtn").onclick=peek;$("resetBtn").onclick=()=>{ki=0;pi=0;renderPuzzle();$("feedback").textContent="もう一回！"};$("replayBtn").onclick=replay;$("againBtn").onclick=restart;loadStage();
